# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1fe0f1a3865062e79b3d061de5dac876a239752ecf6779fea9a484a2c1d3e0a26142508c742ad5103c06c561aafb8ead681f9f89a11d00d1af73c84ef5f41f0

test:
  secret_key_base: 05522acf4b2a0b9a7f0f21146ad7cea57648e7797c7001f2e2eaee5be621154db5e4fd497f9ce25c236193634f38e7c3d5505b8ec2381dc822353ee731deef5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
